CREATE TABLE users(
    id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
    first_name VARCHAR(40) NOT NULL,
    last_name VARCHAR(40) NOT NULL,
    email VARCHAR(60) NOT NULL,
    hashed_password CHAR(60) NOT NULL,
    PRIMARY KEY (id),
    UNIQUE(email)
);
-- @BLOCK
DESCRIBE users;
-- @BLOCK
SELECT *
FROM users;
-- @BLOCK
ALTER TABLE users
MODIFY id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT;
-- @BLOCK
ALTER TABLE users
ADD UNIQUE(email);
-- @BLOCK
DELETE FROM users
WHERE first_name = "EE";